### ISSUE TITLE
Can't configure additional dictionaries

### ISSUE THREAD

**Issue by theseion** [namics/gradle-license-enforce-plugin#6]
Adding additional license dictionaries doesn't work as intended (at least not for me). The docs say that you can provide a list of dictionaries but what you actually expect is a list of files, where each file has a single line with the name of a file that holds a dictionary. See https://github.com/merkle-open/gradle-license-enforce-plugin/blob/bc2326d1bae1a2e583d3336f869a11665a3f708e/src/main/kotlin/com/namics/oss/gradle/license/LicenseEnforceTask.kt#L167

IMO, line 167 should be removed.

I tried to work around the issue by using an extra file in between but I couldn't get it to work; I tried using absolute paths, both windows and unix paths, quotes.... It always fails with :
```
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: additional-license-definitions.yaml
 (The filename, directory name, or volume label syntax is incorrect)
...
Caused by: java.io.FileNotFoundException: additional-license-definitions.yaml
 (The filename, directory name, or volume label syntax is incorrect)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
	at com.namics.oss.gradle.license.LicenseEnforceTask.addConfiguredDictionaries(LicenseEnforceTask.kt:167)
	at com.namics.oss.gradle.license.LicenseEnforceTask.initializeDictionary(LicenseEnforceTask.kt:148)
	at com.namics.oss.gradle.license.LicenseEnforceTask.enforce(LicenseEnforceTask.kt:59)
```

I think the issue might be that you don't trim the line, but that's irrelevant because, as I wrote above, I think you need to remove line 167.

**Comment by andreschaefer** [comment]
Hi @theseion I applied your suggestion next to some other changes. Does this fix work for you?

**Comment by theseion** [comment]
Thanks. I will have to check. I'll probably get around to it next week.
